### ISSUE TITLE
Improve user doc

### ISSUE THREAD

**Issue by krystianity** [iLert/terraform-provider-ilert#1]
- [x] it is not clear that timezones listed are just an example
- [x]  add IANA tz database names to help understand the format
- [x] the mobile block is missing in the description for phone numbers

**Comment by alexs77** [comment]
timezones do NOT just seem to be an example.

In the web frontend, I set the timezone of my user to "Europe/Zurich". Now I'm having this source code:

```hcl
resource "ilert_user" "edienemail" {
  email      = "q2@example.net"
  username   = "edienemail"
  first_name = "John"
  last_name  = "Doe"
  language   = "de"
  role       = "ADMIN"
  timezone   = "Europe/Zurich"
}
```

A `terraform plan` fails:

```
$ terraform plan -lock=false -out=☺
╷
│ Error: "Europe/Zurich" is an invalid value for argument timezone. Must be one of []string{"Europe/Berlin", "America/New_York", "America/Los_Angeles", "Asia/Istanbul"}
│ 
│   with ilert_user.sharedienemail,
│   on iLert.tf line 128, in resource "ilert_user" "edienemail":
│  128:   timezone="Europe/Zurich"
│ 
╵
```

When I don't set `timezone` in the resource, it would reset the value to `Europe/Berlin` and using just Terraform, I wouldn't have a way to set it back to `Europe/Zurich` 

---

The landline block is also missing in the docs.
