### ISSUE TITLE
Exempting public holidays from on-call schedules

### ISSUE THREAD

**Issue by Raghed22** [iLert/terraform-provider-ilert#30]
We would like to exempt holidays from the on-call scheduling.

This API could help you achieve that functionality: https://date.nager.at/api/
Examples:
https://date.nager.at/api/v3/PublicHolidays/2022/SE
https://date.nager.at/api/v3/PublicHolidays/2022/DE

**Comment by BirolYildiz** [comment]
Closing this, as this is a feature request for iLert and not our TF provider.

@Raghed22 feel free to submit ideas at roadmap.ilert.com.
