### ISSUE TITLE
Retrieving a service (not existing) with the terraform provider generates a confusing message

### ISSUE THREAD

**Issue by Raghed22** [iLert/terraform-provider-ilert#32]
Example:
```
data "ilert_service" "service" {
  name = var.ilert_service_name
}
```
Message:
```
│ Error: could not read a service with ID
│
│   with module.uptime-gcp-ilert.data.ilert_service.service,
│   on .terraform/modules/uptime-alert-gcp-ilert/main.tf line 1, in data "ilert_service" "service":
│    1: data "ilert_service" "service" {
```
Comments:
The service was first of all retrieved by name since there are no service retrieval by ID.
I would personally have that error message a customized with the name of the service we are trying to retrieve. Try testing it out with a "for each" and you'll know why I posted this issue🙂

**Comment by STLVRTX** [comment]
Thank you for posting this issue, we have improved these error messages to display the name. It will be rolled out in our next terraform release, Issue will be closed when release happens.
