### ISSUE TITLE
Alert grouping (Time-based) for Alert Sources.

### ISSUE THREAD

**Issue by rauny-brandao** [iLert/terraform-provider-ilert#56]
Hey,

Any plans for having Alert grouping for Alert sources available on Terraform?

![CleanShot 2023-10-05 at 09 06 42@2x](https://github.com/iLert/terraform-provider-ilert/assets/13734862/de4136fe-1056-4b75-92e7-ad54b9d95f0c)

Thank you!

**Comment by STLVRTX** [comment]
Hello,

right now we are working on a couple of new features for our Terraform provider. Time based alert grouping is also part of this batch and will be available soon with the next release.

**Comment by STLVRTX** [comment]
**Update:** Time based alert grouping is now available with the latest provider version [v2.1.0](https://registry.terraform.io/providers/iLert/ilert/latest).
Thank you for your patience, closing this.
