### ISSUE TITLE
Implement retries with backoff on 429 to support larger projects

### ISSUE THREAD

**Issue by krystianity** [iLert/terraform-provider-ilert#6]
See: https://github.com/hashicorp/terraform/issues/1051

Reference implementation:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/7975486/155561488-00d4a7f2-ac34-475f-9feb-d656e20ba450.png">
https://github.com/terraform-providers/terraform-provider-oci

**Comment by yacut** [comment]
released in 1.5.x
