### ISSUE TITLE
Add alert action trigger type alert-escalation-ended and its companion field delaySec

### ISSUE THREAD

**Issue by krystianity** [iLert/terraform-provider-ilert#62]
- delaySec: number > 0 < 7200
- triggerTypes ["alert-escalation-ended"]

https://api.ilert.com/api-docs/#tag/Alert-Actions/paths/~1alert-actions/post

**Comment by STLVRTX** [comment]
Fields now have been implemented and are available as of provider version [v2.2.0](https://registry.terraform.io/providers/iLert/ilert/2.2.0).
