### ISSUE TITLE
Companion field delaySec improvement (lint and doc)

### ISSUE THREAD

**Issue by SpawW** [iLert/terraform-provider-ilert#64]
The [Issue 62](https://github.com/iLert/terraform-provider-ilert/issues/62) add alert action trigger type alert-escalation-ended and its companion field delaySec and is working fine but needs to improve in two things:
1) In VS studio (and others) the new HCL parameter is not reconized

![image](https://github.com/iLert/terraform-provider-ilert/assets/3518964/ea50af6e-7fd4-49cd-961d-88af8436ea6c)
![image](https://github.com/iLert/terraform-provider-ilert/assets/3518964/072b7989-a760-4341-9be0-fec26f730304)

2) In terraform plan **delay_sec** is not checked as mandatory if **trigger_type** is **alert-escalation-ended** and this cause **terraform apply** to fail.
2.1) The minimum value for **delay_sec** to api accept is 1 (I try with 0 and not work), I think this need to be more clear in documentation.

![image](https://github.com/iLert/terraform-provider-ilert/assets/3518964/91018b1b-2f78-47b6-a566-bb125d29a39f)

**Comment by STLVRTX** [comment]
Hello, thank you for submitting an issue.

We've identified an issue when checking the `delaySec` parameter. A fix for this will be released in the next 24 hours.

We are not quite sure why the new parameters are not recognized correctly, we will monitor this closely with the upcoming release.

**Comment by dogmatic69** [comment]
There still seems to be a problem with the logic around this change. Having upgraded to 2.3 I'm getting a similar error and not defining `delay_sec` at all. trigger_types is as follows:

```
trigger_types = [
    "alert-created",
    "alert-acknowledged",
    "alert-auto-resolved",
    "alert-resolved",
  ]
```

Error: [ERROR] Can't set field 'delay_sec' when trigger types do not include type 'alert-escalation-ended'

Is the provider some how setting a default value causing this even though `alert-escalation-ended` is not included?

**Comment by dogmatic69** [comment]
Ok, from 2.3 this is what is happening:

```
$ terraform init
Initializing the backend...
Initializing modules...
Initializing provider plugins...
- Reusing previous version of ilert/ilert from the dependency lock file
- Using previously-installed ilert/ilert v2.3.0
```

from the plan the output looks like this, note delay_sec is not configured at all in the code.

```
  # module.xxx.ilert_alert_action.alert_actions["yyy"] will be created
  + resource "ilert_alert_action" "alert_actions" {
      + created_at    = (known after apply)
      + id            = (known after apply)
      + name          = "Update service and status page"
      + trigger_mode  = "AUTOMATIC"
      + trigger_types = [
          + "alert-created",
          + "alert-acknowledged",
          + "alert-auto-resolved",
          + "alert-resolved",
        ]
      + updated_at    = (known after apply)
      + alert_source {
          + id = (known after apply)
        }
      + automation_rule {
          + alert_type        = "CREATED"
          + resolve_incident  = true
          + send_notification = false
          + service_ids       = (known after apply)
          + service_status    = "PARTIAL_OUTAGE"
          + template_id       = (known after apply)
        }
      + connector {
          + type = "automation_rule"
        }
    }
```

Result from apply is as follows:

```
Error: [ERROR] Can't set field 'delay_sec' when trigger types do not include type 'alert-escalation-ended'
│
│   with module.xxx.ilert_alert_action.alert_actions["yyy"],
│   on .terraform\modules\xxx\modules\monitoring\ilert\resources.tf line 76, in resource "ilert_alert_action" "alert_actions":
│   76: resource "ilert_alert_action" "alert_actions" {
```

**Comment by krystianity** [comment]
Sadly Terraform's `d.GetOk("")` is a pain here, we decided to drop it entirely. And let this check run in the API.
Release 2.3.1 contains the fix.
