### ISSUE TITLE
Run migration to alert actions v2

### ISSUE THREAD

**Issue by krystianity** [iLert/terraform-provider-ilert#68]
alert actions v2 offer multiple alert sources per alert action and even no alert sources at all
they also add team ownerships to alert actions
they expose additional connector types e.g. Slack or MS Teams

-> https://github.com/iLert/terraform-provider-ilert/pull/60

**Comment by STLVRTX** [comment]
Release [v2.6.0](https://registry.terraform.io/providers/iLert/ilert/2.6.0) features migration of alert actions v2, closing as completed.
