### ISSUE TITLE
Endless change detected in schedule

### ISSUE THREAD

**Issue by SpawW** [iLert/terraform-provider-ilert#72]
I have a little strange case.
I have one schedule and all times I run the terraform plan / apply are detect need of changes but don't have any change to do.
The schedule is for:
- user a
- user b
- user a
- user c

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
Terraform will perform the following actions:
  # ilert_schedule.xpto will be updated in-place
  ~ resource "ilert_schedule" "xpto" {
        id        = "id"
        name      = "my_name"
        # (3 unchanged attributes hidden)
      ~ schedule_layer {
            name      = "layer1"
            # (2 unchanged attributes hidden)
          ~ user {
              ~ id = "user a" -> "user c"
            }
          ~ user {
              ~ id = "user b" -> "user a"
            }
          ~ user {
              ~ id = "user c" -> "user b"
            }
          + user {
              + id = "user a"
            }
        }
    }
Plan: 0 to add, 1 to change, 0 to destroy.

----------
When I look in schedules lists... appears to be ok:
![image](https://github.com/iLert/terraform-provider-ilert/assets/3518964/507686af-a7f8-4038-a651-d3ba1ee6e18f)

But, when we look in edit mode... shows only 3 users and a different schedule:
![image](https://github.com/iLert/terraform-provider-ilert/assets/3518964/d00a5e8d-faa3-4f9f-b905-eeff15fb06fd)
---------

So I think we have 2 issues here.
1) a need to improve terraform module to avoid this "fake" change detection
2) a need to improve the ilert site to show the right schedule and right number and order of users in schedule in edit mode.

**Comment by STLVRTX** [comment]
Thank you for submitting an issue, we are currently investigating the underlying problem and will keep you updated with a solution for this.

**Comment by krystianity** [comment]
Fixed, thanks for reporting.
