### ISSUE TITLE
plan fails with 404 error if resource has been deleted/renamed on the web

### ISSUE THREAD

**Issue by alexs77** [iLert/terraform-provider-ilert#8]
I previously used Terraform to create an iLert user "john.doe". It got assigned the ID 1234567.

In the meantime, I deleted this user on the web interface. When I now run `terraform plan` again, it fails:

```
Error: Error occurred with status code: 404, error code: ERROR, message: there is no user with ID or username 1234567

  with ilert_user.shared["john.doe"],
  on users.tf line 5, in resource "ilert_user" "shared":
   5: resource "ilert_user" "shared" {
```

That's not how other providers behave. If I delete a resource on Azure and then run `terraform plan` again, terraform (or the provider?) will notice that the resource is missing and would re-create it.

The iLert provider should behave identical.

**Comment by yacut** [comment]
fixed in v1.5.1
